[package]
org = "kalana_kivindu"
name = "backend"
version = "0.1.0"
distribution = "2201.12.8"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.2.2"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.15.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"
