[package]
org = "kalana_kivindu"
name = "backend"
version = "0.1.0"
distribution = "2201.12.8"

[build-options]
observabilityIncluded = true

# Temporarily commenting out MongoDB dependency due to download issues
# [[dependency]]
# org = "ballerinax"
# name = "mongodb"
# version = "3.0.0"
